ktor:
    application:
        modules:
            - com.serranoie.server.ApplicationKt.module
    deployment:
        port: 8080
        host: "0.0.0.0"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
